freebsd_instance:
  image: freebsd-11-2-release-amd64

task:

  install_script:
    - pkg install -y cmake
    - pkg install -y git
    - pkg install -y ninja
    - pkg install -y yajl

  script:
    - mkdir build && cd build
    - cmake -GNinja -DPLUGINS='ALL' -DTARGET_PLUGIN_FOLDER="" -DCMAKE_SKIP_INSTALL_RPATH=ON ..
    - ninja
    - output="$(ninja install 2>&1)" || printf '%s' "$output"

  tests_script:
    # Work around stalled process plugin and library problems on FreeBSD: https://issues.libelektra.org/2323
    - sudo mount -t fdescfs fdesc /dev/fd
    - cd build && ninja run_all
    - kdb run_all
