freebsd_instance:
  image: freebsd-11-2-release-amd64

task:

  install_script:
    - pkg install -y cmake
    - pkg install -y git
    - pkg install -y ninja
    - pkg install -y yajl

  script:
    - mkdir build && cd build
    # The tests for the process plugin stall on FreeBSD
    - cmake -GNinja -DPLUGINS='ALL;-process' ..
    - ninja

  tests_script:
    - cd build && ctest --output-on-failure -E 'pluginprocess|testmod_network'
